# Generated by Django 3.1.2 on 2020-11-27 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Zip code')),
                ('address1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address #1')),
                ('address2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address #2')),
                ('additional_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='Additional Information')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prof_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
