# Generated by Django 3.1.2 on 2020-11-28 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_auto_20201121_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=40, verbose_name='E-mail')),
                ('delivery', models.CharField(choices=[('pu', 'Self pickup'), ('cr', ' Courrier delivery'), ('pt', 'Postal delivery')], default='pu', max_length=2, verbose_name='Delivery type')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('already_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='orders.cart', verbose_name='Order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
