# Generated by Django 3.1.2 on 2020-12-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20201201_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('stat1', 'Placed'), ('stat2', 'Proccessed'), ('stat3', 'Sent')], default='stat1', max_length=50, verbose_name='Order Status'),
        ),
    ]
