# Generated by Django 3.1.2 on 2020-12-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(default='none', max_length=500, verbose_name='Additional Comments'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('pu', 'Self pickup at Minsk, Pervomayskaya str. 24'), ('cr', ' Courrier delivery'), ('pt', 'Postal delivery')], default='pu', max_length=2, verbose_name='Delivery type'),
        ),
    ]
