# Generated by Django 3.1.2 on 2020-10-21 12:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('refference_db', '0002_age_res_format_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('cover_photo', models.ImageField(upload_to='media/', verbose_name='Cover')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price (BYN)')),
                ('publishing_date', models.DateField(default=datetime.date.today, verbose_name='Date published')),
                ('pages_num', models.PositiveIntegerField(default=0, verbose_name='Number of pages')),
                ('binding', models.CharField(default='', max_length=50, verbose_name='Binding')),
                ('ISBN', models.PositiveIntegerField(default=0, max_length=13, verbose_name='ISBN')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='Weight (g)')),
                ('stock_number', models.PositiveIntegerField(default=0, verbose_name='Left in stock')),
                ('is_active', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Is active?')),
                ('entry_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date of entry')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Date of update')),
                ('age_res', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='refference_db.age_res')),
                ('author_id', models.ManyToManyField(to='refference_db.Author')),
                ('format', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='refference_db.format')),
                ('genre_id', models.ManyToManyField(to='refference_db.Genre')),
                ('publisher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='refference_db.publisher')),
                ('rating', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='refference_db.rating')),
                ('series', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='refference_db.series')),
            ],
        ),
    ]
