# Generated by Django 3.1.2 on 2020-11-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.PositiveIntegerField(default=0, verbose_name='ISBN'),
        ),
    ]
