# Generated by Django 3.1.2 on 2020-10-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refference_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age_res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=50, verbose_name='Age restrictions')),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=50, verbose_name='Format')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=50, verbose_name='Rating')),
            ],
        ),
    ]
