# Generated by Django 3.1.2 on 2020-10-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refference_db', '0002_age_res_format_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='age_res',
            old_name='format',
            new_name='age_res',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='format',
            new_name='rating',
        ),
    ]
